import 'package:flutter/material.dart';

class AppLocalizations {
  const AppLocalizations(this.locale);
  final Locale locale;
  static const supportedLocales = [Locale('en'), Locale('pt'), Locale('th')];
  static const _copy = {
    'en': {
      'appName': 'Certifications',
      'ok': 'OK',
      'menu': 'Menu',
      'about': 'About',
      'logIn': 'Log in',
      'signUp': 'Sign up',
      'close': 'Close',
      'certificates': 'Certificates',
      'plans': 'Plans',
      'support': 'Support',
      'profile': 'Profile',
      'logout': 'Logout',
      'landingImagine': 'Imagine sharing a',
      'landingExample': 'Certified Master of Shrek Quotes',
      'landingCertification': 'certification.',
      'landingSeriousQuestion': 'Or your layer is serious certifications?',
      'landingSeriousBody': 'This is your growth hack entry point.',
      'welcomeTitle': 'Turn material into mastery.',
      'welcomeBody': 'Build a focused study from the material you choose.',
      'signIn': 'Sign in',
      'openStudies': 'Open studies',
      'newStudy': 'New study',
      'studyName': 'Study name',
      'createStudy': 'Create study',
      'myStudiesTitle': 'My Studies',
      'myStudiesSubtitle': 'Everything you are learning, all in one place.',
      'noStudies': 'No studies yet',
      'continueStudy': 'Continue',
      'addSource': 'Add source',
      'upload': 'Upload',
      'pdf': 'PDF',
      'audio': 'Audio',
      'text': 'Text',
      'selectRange': 'Select range',
      'wholeDocument': 'Whole document',
      'process': 'Process source',
      'ready': 'Ready',
      'processing': 'Processing',
      'generate': 'Generate questions',
      'useWeb': 'Use web research',
      'useWebDescription':
          'Allow this quiz generation to use web research when needed.',
      'easy': 'Easy',
      'medium': 'Medium',
      'hard': 'Hard',
      'theme': 'Theme',
      'language': 'Language',
      'appearanceAndLanguage': 'Appearance & language',
      'darkTheme': 'Dark theme',
      'themeDescription':
          'Switch between the light and dark monochrome themes.',
      'system': 'System',
      'light': 'Light',
      'dark': 'Dark',
      'remaining': 'Remaining',
      'score': 'Score',
      'delete': 'Delete',
      'complete': 'Complete study',
      'errorGeneric': 'Something went wrong. Please try again.',
      'retry': 'Retry',
      'loading': 'Loading…',
      'question': 'Question',
      'next': 'Next',
      'finish': 'Finish',
      'diagramUnavailable': 'Diagram unavailable',
      'studyComplete': 'Study completed',
      'memory': 'Study memory',
      'trustTransparency': 'Trust & transparency',
      'trustTitle': 'No provider keys required',
      'trustBody':
          'Certification generation is managed by the application. You never need to paste a model provider key.',
      'privacyTitle': 'Privacy, simply stated',
      'privacyBody':
          'We use your sources only to create your study. Share only what you are comfortable sharing.',
      'howItWorks': 'How it works',
      'whatCreate': 'What you can create',
      'whyDifferent': 'Why it’s different',
      'mvpToday': 'MVP today, more tomorrow',
      'shareAnywhere': 'Share your certifications anywhere.',
      'verifyBeforePublish':
          'Quizzes are AI-generated; verify results before you publish.',
      'learnQuizCertified': 'Learn. Quiz. Get certified.',
      'attachPdf': 'Attach your PDF',
      'takeQuiz': 'Take the quiz',
      'shareCertification': 'Share your certification',
      'availableNow': 'Available now',
      'pdfDocuments': 'PDF documents.',
      'comingNext': 'Coming next',
      'youtubeGeneration': 'YouTube quiz generation.',
      'planFree': 'Free · MVP',
      'cookieMessage':
          'We use cookies to improve your experience and provide essential functionality.',
      'acceptNecessary': 'Accept only necessary',
      'acceptAll': 'Accept all',
      'start': 'Start',
      'end': 'End',
      'plansIntro':
          'Free during the MVP — start a focused study with managed local capacity.',
      'planStudyTitle': 'Study without configuration',
      'planStudyBody':
          'Create a study from your material, generate questions, and finish with a shareable certification.',
      'tier0Capacity': 'Tier 0 · default local capacity',
      'tier12Allowance': 'Tiers 1–2 · small guided allowance',
      'tier35Trial': 'Tiers 3–5 · limited trial capacity',
      'selectPlan': 'Select plan',
      'usePlan': 'Use',
      'currentPlan': 'Current Plan',
      'activePlan': 'Active Plan',
      'waitlistJoined': 'Waitlist Subscribed',
      'planFreeTag': 'Available Now · MVP',
      'planGuidedTag': 'Coming Soon · Guided Phase',
      'planAdvancedTag': 'Coming Soon · Tiers 3–5',
      'chipWebSearch': 'Integrated Web Search',
      'chipPdfSupport': 'Expanded PDF Support',
      'chipPriorityQueue': 'Priority Processing Queue',
      'chipYoutubeQuizzes': 'YouTube Quizzes',
      'chipMultiPdf': 'Multi-PDF Synthesis',
      'chipCustomPrompts': 'Custom Prompt Tuning',
      'chipUnlimitedQuizzes': 'Unlimited Quiz Generation',
      'home': 'Home',
      'studies': 'Studies',
      'joinWaitlist': 'Join the waitlist',
      'waitlistTitle': 'Join the waitlist',
      'waitlistBody':
          'Leave your email and we will keep your place for upcoming plan access.',
      'email': 'Email',
      'emailInvalid': 'Enter a valid email address.',
      'waitlistSuccess': 'Your request was received.',
      'waitlistFailure':
          'We could not record your request. Please try again later.',
      'submit': 'Submit',
      'cancel': 'Cancel',
      'planGuided': 'Guided',
      'planAdvanced': 'Advanced',
      'planGuidedBody':
          'More guided generation and study controls are planned for a future release.',
      'planAdvancedBody':
          'Higher tiers and expanded limits will arrive after the MVP.',
      'playfulBody':
          'Turn anything into a badge. From memes to random notes, transform everyday texts into funny certificates you can show off. Lighthearted, creative, and perfect for sharing laughs.',
      'seriousTitle': 'When knowledge really counts.',
      'seriousBody':
          'Upload books, study materials, or professional texts, then take AI-generated quizzes to prove your skills. Verified results for those who want recognition that matters.',
      'heroSub':
          'Attach a PDF. We create a quiz. Finish it and share a certification with your score.',
      'exCloudSec': 'Cloud Security Fundamentals',
      'exAiBasics': 'AI Basics for Product Teams',
      'exJazzHist': 'Jazz History Essentials',
      'exFilmDir': 'Film Directors: A Quiz',
      'exSpaceExp': 'Space Exploration 101',
      'bulletMaterial': 'Built from your own material.',
      'bulletShareable': 'Shareable, score-based certifications.',
      'bulletMultiple': 'Multiple certifications per user.',
      'bulletFree': 'Start free with managed capacity.',
      'comingNextNotice': 'Coming next (if users want it)',
      'syncing': 'Syncing…',
      'redirecting': 'Redirecting...',
      'pleaseWaitRedirect': 'Please wait while we take you there.',
      'supportTip':
          'Tip: If you encounter any issues, please contact support@asodya.com for assistance.',
      'certAcknowledges': 'This acknowledges that',
      'certCompletedReq':
          'has successfully completed all the requirements to be recognized as a',
      'certOfficer': 'Certification Officer',
      'devErrorTitle': 'Development error',
      'unexpectedProblem':
          'The application hit an unexpected problem. You can send a report to help diagnose it.',
      'contextCopied': 'Error context copied to clipboard.',
      'reportSentSuccess': 'The error report was sent successfully.',
      'reportSentFailure': 'The error report could not be sent right now.',
      'valPropTitle':
          'Your Study Intelligence, Powered by High-Precision AI.',
      'valPropSubtitle':
          'Turn PDFs, books, audio lectures, and videos into practice tests and interactive quizzes in seconds. Study your way, at your speed, hassle-free.',
      'valPropTile1Title': '1. Learn Any Subject in 1 Click',
      'valPropTile1Desc':
          'Forget wasting time creating questions manually. Choose a topic from our suggestion list (like AWS Certifications, Python, ENEM, or Law) or type the subject you want to master.',
      'valPropTile2Title': '2. Study with Your Own Materials',
      'valPropTile2Desc':
          'Have a long PDF, an MP3 lecture recording, a Word document, or a spreadsheet? Simply upload the file and select the exact chapter or minutes you wish to review.',
      'valPropTile3Title': '3. Ultra-Simple Apple-Style Interface',
      'valPropTile3Desc':
          'Designed for maximum efficiency. A modern, clean, and fluid visual experience in 4 simple steps. Switch steps whenever you want without losing filled data.',
      'valPropTile4Title': '4. Smart Dashboard & Quick Resume',
      'valPropTile4Desc':
          'Need to pause your studies? Your draft is saved automatically. With 1 click, resume right where you left off.',
      'valPropTile5Title': '5. Share Securely & Compete on the Leaderboard',
      'valPropTile5Desc':
          'Create private quizzes with secure links that expire automatically or publish your practice tests to the Asodya community catalog and compete on the Official Leaderboard!',
      'valPropCtaGetStarted': '✨ Get Started Free',
      'valPropCtaJoinWaitlist': '📋 Join Pro Waitlist',
      'step1Title': '1. Choose Your Topic',
      'step2Title': '2. Choose Your Source',
      'step3Title': '3. Format & Difficulty',
      'step4Title': '4. Review & Generate',
      'sourceUpload': 'Upload my own material',
      'questionCount': 'Number of questions',
      'questionsSuffixLabel': 'questions',
      'generateQuizNow': 'Generate Quiz Now',
      'resetWizard': 'Reset wizard',
      'resetWizardConfirm':
          'This clears all your progress and returns to Step 1. This cannot be undone.',
      'wizardTitle': 'Create New Quiz',
      'studyNameHint': 'e.g. Software Architecture / Cell Biology',
      'sourceUploadHint': 'PDF, DOCX, CSV, TXT, MD, MP3, WAV, M4A, MP4, MOV',
      'difficultyLabel': 'Difficulty:',
      'reviewThemeLabel': '📌 Topic:',
      'reviewSourceLabel': '📄 Source:',
      'reviewLevelLabel': '🎯 Level:',
      'reviewVisibilityLabel': '🔒 Visibility:',
      'reviewFilesCountLabel': '{count} file(s): {names}',
      'rangeSelectorTitle': 'Which part do you want to use?',
      'pageStartLabel': 'Start Page',
      'pageEndLabel': 'End Page',
      'rangeUntil': 'to',
      'lineStartLabel': 'Start Line',
      'lineEndLabel': 'End Line',
      'timeRangeLabel': 'Time Range:',
      'removeFile': 'Remove file',
      'addFiles': 'Add files',
      'filesCapUsageLabel': '{used} MB of {cap} MB used',
      'capExceededWarning':
          'Adding this file would exceed the 150MB limit for this study.',
      'tapFileToConfigureHint':
          'Tap a file to select a specific range instead of the whole document.',
      'noFilesAddedYet': 'No files added yet. Tap Add files to get started.',
      'questionCountMax': 'Max',
      'questionCountMaxLabel': 'As many as the material supports',
      'visibilityPublicWarning':
          'Once someone else attempts a public quiz, it can no longer be deleted, to preserve leaderboard history.',
      'completedMetrics': 'Completed Metrics',
      'standbyStudies': 'Standby Studies',
      'quickInfo': 'Quick info',
      'addFile': 'Add file',
      'startQuiz': 'Start quiz',
      'cortexConnected': 'AI Cortex Connected',
      'studyNotebooksLabel': 'Study Notebooks',
      'storageUsedLabel': 'FSM Storage Used',
      'completedQuizzesLabel': 'Completed Quizzes',
      'averageScoreLabel': 'Average Score',
      'noScoreDataTooltip': 'No completed quizzes yet, so there is no score to average.',
      'dashboardEmptyState': 'Your dashboard will come alive once you start a study.',
      'studiesBreakdownTooltip': '{standby} in standby, {completed} completed',
      'deleteStudyConfirm': 'Do you really want to delete the study "{name}"?',
      'studyDeletedSuccess': 'Study removed successfully.',
      'fileAttachedSuccess': 'File attached successfully.',
      'attachedSourcesLabel': 'Attached Files and Sources ({count}):',
      'noFilesAttachedYet': 'No files attached yet.',
      'mbUsedLabel': 'MB used',
      'lastOpenedLabel': 'Last opened: {date}',
      'noStudiesSubtitle': 'Create your first study to get started.',
      'selectStudiesAction': 'Select',
      'selectedCountLabel': '{count} selected',
      'deleteSelectedAction': 'Delete selected',
      'deleteSelectedConfirm': 'Delete {count} selected studies? This cannot be undone.',
      'searchStudiesHint': 'Search your studies…',
      'noSearchResultsLabel': 'No studies match "{query}".',
      'editStudy': 'Edit study',
      'renameStudyLabel': 'Study name',
      'saveChanges': 'Save changes',
      'resumeHeroTitle': 'Resume where you left off',
      'resumeHeroSubtitle':
          'Pick up your most recent draft right where you paused it.',
      'resumeHeroCta': 'Resume now',
      'editSourceRangesLabel': 'Selected ranges',
      'expiration24h': '24 hours (short term)',
      'expiration7d': '7 days (1 week)',
      'expiration30d': '30 days (1 month)',
      'expirationOneUse': '1 use only',
      'expirationLabel': 'Link expiration:',
      'shareModalSubtitle': 'Share: "{title}"',
      'generateSecureLink': 'Generate secure expiring link',
      'regenerateLink': 'Regenerate link',
      'linkCopied': 'Link copied to clipboard!',
      'noParticipantsYet': 'No participant has completed this quiz yet.',
      'timePrefix': 'Time:',
      'visibilityLabel': 'Visibility',
      'visibilityPrivate': 'Private',
      'visibilityPublic': 'Public',
      'deleteProtectedTooltip':
          'Public quizzes with active participant attempts cannot be deleted to preserve leaderboard history.',
      'completedQuizzesTitle': 'Completed quizzes',
      'shareLink': 'Share link',
      'leaderboard': 'Leaderboard',
      'shareAction': 'Share',
      'leaderboardAction': 'View leaderboard',
      'viewCompletedQuizzes': 'View completed quizzes',
      'noCompletedQuizzesYet': 'You have no completed quizzes yet.',
      'yourCertificatesLabel': 'Your Certificates',
      'expandDashboard': 'Expand',
      'collapseDashboard': 'Collapse',
      'completedOnLabel': 'Completed on',
      'totalAttemptsLabel': 'Total attempts',
    },
    'pt': {
      'appName': 'Certifications',
      'ok': 'OK',
      'menu': 'Menu',
      'about': 'Sobre',
      'logIn': 'Entrar',
      'signUp': 'Criar conta',
      'close': 'Fechar',
      'certificates': 'Certificados',
      'plans': 'Planos',
      'support': 'Suporte',
      'profile': 'Perfil',
      'logout': 'Sair',
      'landingImagine': 'Imagine compartilhar uma',
      'landingExample': 'Mestre Certificado em Frases do Shrek',
      'landingCertification': 'certificação.',
      'landingSeriousQuestion': 'Ou a sua área exige certificações sérias?',
      'landingSeriousBody': 'Este é o ponto de partida para seu crescimento.',
      'welcomeTitle': 'Transforme material em domínio.',
      'welcomeBody': 'Crie um estudo focado com o material que você escolher.',
      'signIn': 'Entrar',
      'openStudies': 'Abrir estudos',
      'newStudy': 'Novo estudo',
      'studyName': 'Nome do estudo',
      'createStudy': 'Criar estudo',
      'myStudiesTitle': 'Meus Estudos',
      'myStudiesSubtitle': 'Tudo o que você está estudando, em um só lugar.',
      'noStudies': 'Nenhum estudo ainda',
      'continueStudy': 'Continuar',
      'addSource': 'Adicionar fonte',
      'upload': 'Enviar',
      'pdf': 'PDF',
      'audio': 'Áudio',
      'text': 'Texto',
      'selectRange': 'Selecionar trecho',
      'wholeDocument': 'Documento inteiro',
      'process': 'Processar fonte',
      'ready': 'Pronto',
      'processing': 'Processando',
      'generate': 'Gerar perguntas',
      'useWeb': 'Usar pesquisa na web',
      'useWebDescription':
          'Permite que esta geração use pesquisa na web quando necessário.',
      'easy': 'Fácil',
      'medium': 'Médio',
      'hard': 'Difícil',
      'theme': 'Tema',
      'language': 'Idioma',
      'appearanceAndLanguage': 'Aparência e idioma',
      'darkTheme': 'Tema escuro',
      'themeDescription':
          'Alterne entre os temas monocromáticos claro e escuro.',
      'system': 'Sistema',
      'light': 'Claro',
      'dark': 'Escuro',
      'remaining': 'Restante',
      'score': 'Pontuação',
      'delete': 'Excluir',
      'complete': 'Concluir estudo',
      'errorGeneric': 'Algo deu errado. Tente novamente.',
      'retry': 'Tentar novamente',
      'loading': 'Carregando…',
      'question': 'Pergunta',
      'next': 'Próxima',
      'finish': 'Finalizar',
      'diagramUnavailable': 'Diagrama indisponível',
      'studyComplete': 'Estudo concluído',
      'memory': 'Memória do estudo',
      'trustTransparency': 'Confiança e transparência',
      'trustTitle': 'Nenhuma chave de provedor necessária',
      'trustBody':
          'A geração da certificação é gerenciada pelo aplicativo. Você não precisa colar uma chave de provedor.',
      'privacyTitle': 'Privacidade sem complicação',
      'privacyBody':
          'Usamos suas fontes apenas para criar seu estudo. Compartilhe somente o que se sentir confortável.',
      'howItWorks': 'Como funciona',
      'whatCreate': 'O que você pode criar',
      'whyDifferent': 'Por que é diferente',
      'mvpToday': 'MVP hoje, mais amanhã',
      'shareAnywhere': 'Compartilhe suas certificações em qualquer lugar.',
      'verifyBeforePublish':
          'Os quizzes são gerados por IA; verifique os resultados antes de publicar.',
      'learnQuizCertified': 'Aprenda. Faça o quiz. Certifique-se.',
      'attachPdf': 'Anexe seu PDF',
      'takeQuiz': 'Faça o quiz',
      'shareCertification': 'Compartilhe sua certificação',
      'availableNow': 'Disponível agora',
      'pdfDocuments': 'Documentos PDF.',
      'comingNext': 'A seguir',
      'youtubeGeneration': 'Geração de quizzes do YouTube.',
      'planFree': 'Grátis · MVP',
      'cookieMessage':
          'Usamos cookies para melhorar sua experiência e fornecer funções essenciais.',
      'acceptNecessary': 'Aceitar somente necessárias',
      'acceptAll': 'Aceitar todas',
      'start': 'Início',
      'end': 'Fim',
      'plansIntro':
          'Grátis durante o MVP — comece um estudo focado com capacidade local gerenciada.',
      'planStudyTitle': 'Estude sem configuração',
      'planStudyBody':
          'Crie um estudo com seu material, gere perguntas e conclua com uma certificação compartilhável.',
      'tier0Capacity': 'Tier 0 · capacidade local padrão',
      'tier12Allowance': 'Tiers 1–2 · pequena cota guiada',
      'tier35Trial': 'Tiers 3–5 · capacidade de teste limitada',
      'selectPlan': 'Selecionar plano',
      'joinWaitlist': 'Entrar na lista de espera',
      'waitlistTitle': 'Entrar na lista de espera',
      'waitlistBody':
          'Informe seu e-mail para reservar seu lugar no acesso aos próximos planos.',
      'email': 'E-mail',
      'emailInvalid': 'Informe um e-mail válido.',
      'waitlistSuccess': 'Sua solicitação foi recebida.',
      'waitlistFailure':
          'Não foi possível registrar sua solicitação. Tente novamente mais tarde.',
      'submit': 'Enviar',
      'cancel': 'Cancelar',
      'planGuided': 'Guiado',
      'planAdvanced': 'Avançado',
      'usePlan': 'Usar',
      'currentPlan': 'Plano Atual',
      'activePlan': 'Plano Ativo',
      'waitlistJoined': 'Inscrito na Lista de Espera',
      'planFreeTag': 'Disponível Agora · MVP',
      'planGuidedTag': 'Em breve · Fase Guiada',
      'planAdvancedTag': 'Em breve · Tiers 3–5',
      'chipWebSearch': 'Pesquisa Web Integrada',
      'chipPdfSupport': 'Suporte Expandido a PDFs',
      'chipPriorityQueue': 'Fila Prioritária de Processamento',
      'chipYoutubeQuizzes': 'Quizzes do YouTube',
      'chipMultiPdf': 'Síntese de Múltiplos PDFs',
      'chipCustomPrompts': 'Prompts Customizados',
      'chipUnlimitedQuizzes': 'Geração Ilimitada de Quizzes',
      'home': 'Início',
      'studies': 'Estudos',
      'planGuidedBody':
          'Geração mais guiada e novos controles de estudo estão planejados para uma versão futura.',
      'planAdvancedBody':
          'Tiers mais altos e limites ampliados chegarão depois do MVP.',
      'planComingSoon': 'Em breve',
      'planUnavailable': 'A seleção ainda não está disponível.',
      'playfulBody':
          'Transforme qualquer coisa em um selo. De memes a anotações aleatórias, transforme textos do dia a dia em certificados divertidos para exibir. Leve, criativo e perfeito para compartilhar risadas.',
      'seriousTitle': 'Quando o conhecimento realmente importa.',
      'seriousBody':
          'Envie livros, materiais de estudo ou textos profissionais e faça quizzes gerados por IA para comprovar suas habilidades. Resultados verificados para quem busca reconhecimento de valor.',
      'heroSub':
          'Anexe um PDF. Nós criamos um quiz. Conclua e compartilhe uma certificação com sua pontuação.',
      'exCloudSec': 'Fundamentos de Segurança em Nuvem',
      'exAiBasics': 'Básicos de IA para Equipes de Produto',
      'exJazzHist': 'História Essencial do Jazz',
      'exFilmDir': 'Diretores de Cinema: Quiz',
      'exSpaceExp': 'Exploração Espacial 101',
      'bulletMaterial': 'Construído a partir do seu próprio material.',
      'bulletShareable': 'Certificações compartilháveis com pontuação.',
      'bulletMultiple': 'Múltiplas certificações por usuário.',
      'bulletFree': 'Comece grátis com capacidade gerenciada.',
      'comingNextNotice': 'Em breve (conforme demanda dos usuários)',
      'syncing': 'Sincronizando…',
      'redirecting': 'Redirecionando...',
      'pleaseWaitRedirect': 'Aguarde enquanto redirecionamos você.',
      'supportTip':
          'Dica: Se encontrar problemas, entre em contato com support@asodya.com para obter ajuda.',
      'certAcknowledges': 'Certificamos que',
      'certCompletedReq':
          'concluiu com êxito todos os requisitos para ser reconhecido(a) como',
      'certOfficer': 'Oficial de Certificação',
      'devErrorTitle': 'Erro de desenvolvimento',
      'unexpectedProblem':
          'O aplicativo encontrou um problema inesperado. Você pode enviar um relatório para ajudar no diagnóstico.',
      'contextCopied':
          'Contexto do erro copiado para a área de transferência.',
      'reportSentSuccess': 'O relatório de erro foi enviado com sucesso.',
      'reportSentFailure':
          'Não foi possível enviar o relatório de erro no momento.',
      'valPropTitle':
          'Sua Inteligência de Estudos, Potencializada por IA de Alta Precisão.',
      'valPropSubtitle':
          'Transforme PDFs, livros, aulas em áudio e vídeos em simulados e quizzes interativos em segundos. Estude do seu jeito, no seu ritmo e sem complicação.',
      'valPropTile1Title': '1. Aprenda Qualquer Assunto em 1 Clique',
      'valPropTile1Desc':
          'Esqueça a perda de tempo criando perguntas manualmente. Escolha um tema em nossa lista de sugestões (como Certificações AWS, Python, ENEM ou Direito) ou digite o assunto que deseja dominar.',
      'valPropTile2Title': '2. Estude com Seus Próprios Materiais',
      'valPropTile2Desc':
          'Possui um PDF extenso, uma aula gravada em MP3, um documento Word ou uma planilha? Basta carregar o arquivo e selecionar exatamente o capítulo ou os minutos que deseja revisar.',
      'valPropTile3Title': '3. Interface Ultra-Simples Estilo Apple',
      'valPropTile3Desc':
          'Desenhado para quem busca máxima eficiência. Uma experiência visual moderna, limpa e fluida em 4 passos simples. Mude de etapa quando quiser sem perder o que já preencheu.',
      'valPropTile4Title': '4. Dashboard Inteligente & Retomada Rápida',
      'valPropTile4Desc':
          'Precisou pausar os estudos? Seu rascunho fica salvo automaticamente. Com 1 clique, você retoma o preenchimento exatamente no ponto onde parou.',
      'valPropTile5Title':
          '5. Compartilhe com Segurança e Dispute o Ranking',
      'valPropTile5Desc':
          'Crie quizzes privados com links seguros que expiram automaticamente ou publique seus simulados no catálogo da comunidade Asodya e dispute o Ranking Oficial!',
      'valPropCtaGetStarted': '✨ Começar Grátis',
      'valPropCtaJoinWaitlist': '📋 Entrar na Lista Pro',
      'step1Title': '1. Escolha o Tema',
      'step2Title': '2. Escolha a Fonte',
      'step3Title': '3. Formato e Dificuldade',
      'step4Title': '4. Revisão e Geração',
      'sourceUpload': 'Enviar meu próprio material',
      'questionCount': 'Quantidade de perguntas',
      'questionsSuffixLabel': 'perguntas',
      'generateQuizNow': 'Gerar Quiz Agora',
      'resetWizard': 'Reiniciar assistente',
      'resetWizardConfirm':
          'Isso apaga todo o seu progresso e volta para a Etapa 1. Essa ação não pode ser desfeita.',
      'wizardTitle': 'Criar Novo Quiz',
      'studyNameHint': 'ex: Arquitetura de Software / Biologia Celular',
      'sourceUploadHint': 'PDF, DOCX, CSV, TXT, MD, MP3, WAV, M4A, MP4, MOV',
      'difficultyLabel': 'Dificuldade:',
      'reviewThemeLabel': '📌 Tema:',
      'reviewSourceLabel': '📄 Fonte:',
      'reviewLevelLabel': '🎯 Nível:',
      'reviewVisibilityLabel': '🔒 Visibilidade:',
      'reviewFilesCountLabel': '{count} arquivo(s): {names}',
      'rangeSelectorTitle': 'Qual trecho você deseja utilizar?',
      'pageStartLabel': 'Página Inicial',
      'pageEndLabel': 'Página Final',
      'rangeUntil': 'até',
      'lineStartLabel': 'Linha Inicial',
      'lineEndLabel': 'Linha Final',
      'timeRangeLabel': 'Intervalo de Tempo:',
      'removeFile': 'Remover arquivo',
      'addFiles': 'Adicionar arquivos',
      'filesCapUsageLabel': '{used} MB de {cap} MB usados',
      'capExceededWarning':
          'Adicionar este arquivo ultrapassaria o limite de 150MB deste estudo.',
      'tapFileToConfigureHint':
          'Toque em um arquivo para selecionar um trecho específico em vez do documento inteiro.',
      'noFilesAddedYet':
          'Nenhum arquivo adicionado ainda. Toque em Adicionar arquivos para começar.',
      'questionCountMax': 'Máx',
      'questionCountMaxLabel': 'Tantas quanto o material permitir',
      'visibilityPublicWarning':
          'Assim que outra pessoa responder um quiz público, ele não poderá mais ser excluído, para preservar o histórico do ranking.',
      'completedMetrics': 'Métricas Concluídas',
      'standbyStudies': 'Estudos em Espera',
      'quickInfo': 'Info rápida',
      'addFile': 'Adicionar arquivo',
      'startQuiz': 'Iniciar quiz',
      'cortexConnected': 'Cortex IA Conectado',
      'studyNotebooksLabel': 'Cadernos de Estudo',
      'storageUsedLabel': 'Espaço Usado FSM',
      'completedQuizzesLabel': 'Simulados Concluídos',
      'averageScoreLabel': 'Média de Acertos',
      'noScoreDataTooltip': 'Ainda não há simulados concluídos, então não há média para calcular.',
      'dashboardEmptyState': 'Seu painel ganha vida assim que você iniciar um estudo.',
      'studiesBreakdownTooltip': '{standby} em espera, {completed} concluídos',
      'deleteStudyConfirm':
          'Deseja realmente excluir o estudo "{name}"?',
      'studyDeletedSuccess': 'Estudo removido com sucesso.',
      'fileAttachedSuccess': 'Arquivo anexado com sucesso.',
      'attachedSourcesLabel': 'Arquivos e Fontes Anexadas ({count}):',
      'noFilesAttachedYet': 'Nenhum arquivo anexado ainda.',
      'mbUsedLabel': 'MB Usados',
      'lastOpenedLabel': 'Aberto pela última vez em: {date}',
      'noStudiesSubtitle': 'Crie seu primeiro estudo para começar.',
      'selectStudiesAction': 'Selecionar',
      'selectedCountLabel': '{count} selecionado(s)',
      'deleteSelectedAction': 'Excluir selecionados',
      'deleteSelectedConfirm':
          'Excluir {count} estudos selecionados? Essa ação não pode ser desfeita.',
      'searchStudiesHint': 'Buscar nos seus estudos…',
      'noSearchResultsLabel': 'Nenhum estudo corresponde a "{query}".',
      'editStudy': 'Editar estudo',
      'renameStudyLabel': 'Nome do estudo',
      'saveChanges': 'Salvar alterações',
      'resumeHeroTitle': 'Retome de onde parou',
      'resumeHeroSubtitle':
          'Continue seu rascunho mais recente exatamente de onde você pausou.',
      'resumeHeroCta': 'Retomar agora',
      'editSourceRangesLabel': 'Trechos selecionados',
      'expiration24h': '24 Horas (Curto Prazo)',
      'expiration7d': '7 Dias (1 Semana)',
      'expiration30d': '30 Dias (1 Mês)',
      'expirationOneUse': 'Uso único (1 vez)',
      'expirationLabel': 'Tempo de Expiração do Link:',
      'shareModalSubtitle': 'Compartilhar: "{title}"',
      'generateSecureLink': 'Gerar Link Seguro Expirável',
      'regenerateLink': 'Regerar Link',
      'linkCopied': 'Link copiado para a área de transferência!',
      'noParticipantsYet': 'Nenhum participante concluiu este simulado ainda.',
      'timePrefix': 'Tempo:',
      'visibilityLabel': 'Visibilidade',
      'visibilityPrivate': 'Privado',
      'visibilityPublic': 'Público',
      'deleteProtectedTooltip':
          'Quizzes públicos com participações ativas de terceiros não podem ser excluídos, para preservar o histórico do ranking.',
      'completedQuizzesTitle': 'Simulados concluídos',
      'shareLink': 'Compartilhar link',
      'leaderboard': 'Ranking',
      'shareAction': 'Compartilhar',
      'leaderboardAction': 'Ver ranking',
      'viewCompletedQuizzes': 'Ver simulados concluídos',
      'noCompletedQuizzesYet': 'Você ainda não tem simulados concluídos.',
      'yourCertificatesLabel': 'Seus Certificados',
      'expandDashboard': 'Expandir',
      'collapseDashboard': 'Recolher',
      'completedOnLabel': 'Concluído em',
      'totalAttemptsLabel': 'Total de tentativas',
    },
    'th': {
      'appName': 'Certifications',
      'ok': 'ตกลง',
      'menu': 'เมนู',
      'about': 'เกี่ยวกับ',
      'logIn': 'เข้าสู่ระบบ',
      'signUp': 'สมัครใช้งาน',
      'close': 'ปิด',
      'certificates': 'ใบรับรอง',
      'plans': 'แผน',
      'support': 'ช่วยเหลือ',
      'profile': 'โปรไฟล์',
      'logout': 'ออกจากระบบ',
      'landingImagine': 'ลองนึกภาพการแชร์',
      'landingExample': 'ผู้เชี่ยวชาญคำคมเชร็คที่ได้รับการรับรอง',
      'landingCertification': 'ใบรับรอง',
      'landingSeriousQuestion': 'หรือสาขาของคุณต้องการใบรับรองที่จริงจัง?',
      'landingSeriousBody': 'นี่คือจุดเริ่มต้นของการเติบโตของคุณ',
      'welcomeTitle': 'เปลี่ยนเนื้อหาให้เป็นความเชี่ยวชาญ',
      'welcomeBody': 'สร้างการเรียนรู้ที่มีสมาธิจากเนื้อหาที่คุณเลือก',
      'signIn': 'เข้าสู่ระบบ',
      'openStudies': 'เปิดการเรียน',
      'newStudy': 'การเรียนใหม่',
      'studyName': 'ชื่อการเรียน',
      'createStudy': 'สร้างการเรียน',
      'myStudiesTitle': 'การเรียนของฉัน',
      'myStudiesSubtitle': 'ทุกสิ่งที่คุณกำลังเรียนรู้ อยู่ในที่เดียว',
      'noStudies': 'ยังไม่มีการเรียน',
      'continueStudy': 'ดำเนินการต่อ',
      'addSource': 'เพิ่มแหล่งข้อมูล',
      'upload': 'อัปโหลด',
      'pdf': 'PDF',
      'audio': 'เสียง',
      'text': 'ข้อความ',
      'selectRange': 'เลือกช่วง',
      'wholeDocument': 'เอกสารทั้งหมด',
      'process': 'ประมวลผลแหล่งข้อมูล',
      'ready': 'พร้อม',
      'processing': 'กำลังประมวลผล',
      'generate': 'สร้างคำถาม',
      'useWeb': 'ใช้การค้นหาบนเว็บ',
      'useWebDescription':
          'อนุญาตให้การสร้างแบบทดสอบนี้ใช้การค้นหาบนเว็บเมื่อจำเป็น',
      'easy': 'ง่าย',
      'medium': 'ปานกลาง',
      'hard': 'ยาก',
      'theme': 'ธีม',
      'language': 'ภาษา',
      'appearanceAndLanguage': 'รูปแบบและภาษา',
      'darkTheme': 'ธีมมืด',
      'themeDescription': 'สลับระหว่างธีมขาวดำสว่างและมืด',
      'system': 'ระบบ',
      'light': 'สว่าง',
      'dark': 'มืด',
      'remaining': 'คงเหลือ',
      'score': 'คะแนน',
      'delete': 'ลบ',
      'complete': 'เรียนจบ',
      'errorGeneric': 'เกิดข้อผิดพลาด โปรดลองอีกครั้ง',
      'retry': 'ลองอีกครั้ง',
      'loading': 'กำลังโหลด…',
      'question': 'คำถาม',
      'next': 'ถัดไป',
      'finish': 'เสร็จสิ้น',
      'diagramUnavailable': 'แผนภาพไม่พร้อมใช้งาน',
      'studyComplete': 'เรียนจบแล้ว',
      'memory': 'ความจำการเรียน',
      'trustTransparency': 'ความน่าเชื่อถือและความโปร่งใส',
      'trustTitle': 'ไม่ต้องใช้คีย์ผู้ให้บริการ',
      'trustBody':
          'แอปจัดการการสร้างใบรับรองให้เอง คุณไม่จำเป็นต้องวางคีย์ของผู้ให้บริการโมเดล',
      'privacyTitle': 'ความเป็นส่วนตัวอย่างชัดเจน',
      'privacyBody':
          'เราใช้แหล่งข้อมูลของคุณเพื่อสร้างการเรียนเท่านั้น แชร์เฉพาะสิ่งที่คุณสบายใจ',
      'howItWorks': 'วิธีการทำงาน',
      'whatCreate': 'สิ่งที่คุณสร้างได้',
      'whyDifferent': 'ทำไมจึงแตกต่าง',
      'mvpToday': 'MVP วันนี้ พรุ่งนี้ยิ่งดีขึ้น',
      'shareAnywhere': 'แชร์ใบรับรองของคุณได้ทุกที่',
      'verifyBeforePublish': 'แบบทดสอบสร้างโดย AI โปรดตรวจสอบผลก่อนเผยแพร่',
      'learnQuizCertified': 'เรียนรู้ ทำแบบทดสอบ รับใบรับรอง',
      'attachPdf': 'แนบ PDF ของคุณ',
      'takeQuiz': 'ทำแบบทดสอบ',
      'shareCertification': 'แชร์ใบรับรอง',
      'availableNow': 'พร้อมใช้งานแล้ว',
      'pdfDocuments': 'เอกสาร PDF',
      'comingNext': 'ถัดไป',
      'youtubeGeneration': 'การสร้างแบบทดสอบจาก YouTube',
      'planFree': 'ฟรี · MVP',
      'cookieMessage':
          'เราใช้คุกกี้เพื่อปรับปรุงประสบการณ์และให้ฟังก์ชันที่จำเป็น',
      'acceptNecessary': 'ยอมรับเฉพาะที่จำเป็น',
      'acceptAll': 'ยอมรับทั้งหมด',
      'start': 'เริ่มต้น',
      'end': 'สิ้นสุด',
      'plansIntro':
          'ฟรีในช่วง MVP — เริ่มการเรียนรู้แบบโฟกัสด้วยความจุในเครื่อง',
      'planStudyTitle': 'เรียนรู้โดยไม่ต้องตั้งค่า',
      'planStudyBody':
          'สร้างการเรียนจากเนื้อหา สร้างคำถาม และจบด้วยใบรับรองที่แชร์ได้',
      'tier0Capacity': 'Tier 0 · ความจุในเครื่องเริ่มต้น',
      'tier12Allowance': 'Tier 1–2 · โควตาแนะนำขนาดเล็ก',
      'tier35Trial': 'Tier 3–5 · ความจุทดลองแบบจำกัด',
      'selectPlan': 'เลือกแผน',
      'joinWaitlist': 'เข้าร่วมรายการรอ',
      'waitlistTitle': 'เข้าร่วมรายการรอ',
      'waitlistBody': 'กรอกอีเมลเพื่อรับสิทธิ์เข้าถึงแผนในอนาคต',
      'email': 'อีเมล',
      'emailInvalid': 'กรุณากรอกอีเมลที่ถูกต้อง',
      'waitlistSuccess': 'ได้รับคำขอของคุณแล้ว',
      'waitlistFailure': 'ไม่สามารถบันทึกคำขอได้ โปรดลองอีกครั้งภายหลัง',
      'submit': 'ส่ง',
      'cancel': 'ยกเลิก',
      'planGuided': 'แนะนำ',
      'planAdvanced': 'ขั้นสูง',
      'usePlan': 'ใช้งาน',
      'currentPlan': 'แผนปัจจุบัน',
      'activePlan': 'แผนที่ใช้งานอยู่',
      'waitlistJoined': 'ลงทะเบียนในรายการรอแล้ว',
      'planFreeTag': 'เปิดใช้งานแล้ว · MVP',
      'planGuidedTag': 'เร็ว ๆ นี้ · ระยะแนะนำ',
      'planAdvancedTag': 'เร็ว ๆ นี้ · Tier 3–5',
      'chipWebSearch': 'ค้นหาเว็บในตัว',
      'chipPdfSupport': 'รองรับ PDF เพิ่มเติม',
      'chipPriorityQueue': 'คิวประมวลผลด่วน',
      'chipYoutubeQuizzes': 'แบบทดสอบจาก YouTube',
      'chipMultiPdf': 'สังเคราะห์หลาย PDF',
      'chipCustomPrompts': 'ปรับแต่ง Prompt',
      'chipUnlimitedQuizzes': 'สร้างแบบทดสอบไม่จำกัด',
      'home': 'หน้าแรก',
      'studies': 'การเรียน',
      'planGuidedBody':
          'การสร้างที่มีคำแนะนำมากขึ้นและการควบคุมการเรียนจะมาในรุ่นถัดไป',
      'planAdvancedBody': 'Tier ที่สูงขึ้นและขีดจำกัดที่เพิ่มขึ้นจะมาหลัง MVP',
      'planComingSoon': 'เร็ว ๆ นี้',
      'planUnavailable': 'ยังไม่สามารถเลือกได้',
      'playfulBody':
          'เปลี่ยนทุกอย่างให้เป็นตราประทับ จากมีมสู่โน้ตทั่วไป แปลงข้อความประจำวันให้เป็นใบรับรองตลกๆ เพื่ออวดเพื่อนๆ สดใส สร้างสรรค์ และเหมาะสำหรับแบ่งปันเสียงหัวเราะ',
      'seriousTitle': 'เมื่อความรู้มีความหมายจริงๆ',
      'seriousBody':
          'อัปโหลดหนังสือ เอกสารการเรียน หรือข้อความวิชาชีพ แล้วทำแบบทดสอบที่สร้างโดย AI เพื่อพิสูจน์ทักษะของคุณ ผลลัพธ์ที่ได้รับการตรวจสอบสำหรับผู้ที่ต้องการการยอมรับที่มีความหมาย',
      'heroSub':
          'แนบ PDF เราสร้างแบบทดสอบ ทำแบบทดสอบให้เสร็จและแชร์ใบรับรองพร้อมคะแนนของคุณ',
      'exCloudSec': 'พื้นฐานความปลอดภัยบนคลาวด์',
      'exAiBasics': 'พื้นฐาน AI สำหรับทีมผลิตภัณฑ์',
      'exJazzHist': 'ประวัติศาสตร์แจ๊สเบื้องต้น',
      'exFilmDir': 'ผู้กำกับภาพยนตร์: แบบทดสอบ',
      'exSpaceExp': 'การสำรวจอวกาศ 101',
      'bulletMaterial': 'สร้างขึ้นจาก material ของคุณเอง',
      'bulletShareable': 'ใบรับรองที่แชร์ได้พร้อมคะแนน',
      'bulletMultiple': 'หลายใบรับรองต่อผู้ใช้',
      'bulletFree': 'เริ่มต้นฟรีพร้อมความจุที่จัดการได้',
      'comingNextNotice': 'ถัดไป (หากผู้ใช้ต้องการ)',
      'syncing': 'กำลังซิงค์…',
      'redirecting': 'กำลังเปลี่ยนหน้า...',
      'pleaseWaitRedirect': 'โปรดรอสักครู่ขณะนำคุณไปยังหน้าถัดไป',
      'supportTip':
          'คำแนะนำ: หากพบปัญหา โปรดติดต่อ support@asodya.com เพื่อขอความช่วยเหลือ',
      'certAcknowledges': 'ขอรับรองว่า',
      'certCompletedReq':
          'ได้สำเร็จข้อกำหนดทั้งหมดเพื่อได้รับการรับรองเป็น',
      'certOfficer': 'เจ้าหน้าที่ออกใบรับรอง',
      'devErrorTitle': 'ข้อผิดพลาดในการพัฒนา',
      'unexpectedProblem':
          'แอปพลิเคชันพบปัญหาไม่คาดคิด คุณสามารถส่งรายงานเพื่อช่วยวินิจฉัยได้',
      'contextCopied': 'คัดลอกบริบทข้อผิดพลาดไปยังคลิปบอร์ดแล้ว',
      'reportSentSuccess': 'ส่งรายงานข้อผิดพลาดเรียบร้อยแล้ว',
      'reportSentFailure': 'ไม่สามารถส่งรายงานข้อผิดพลาดได้ในขณะนี้',
      'valPropTitle':
          'ภูมิปัญญาการเรียนรู้ของคุณ ขับเคลื่อนด้วย AI ความแม่นยำสูง',
      'valPropSubtitle':
          'เปลี่ยน PDF หนังสือ การบรรยายเสียง และวิดีโอให้เป็นแบบทดสอบและควิซแบบโต้ตอบได้ในไม่กี่วินาที เรียนในแบบของคุณ ตามจังหวะของคุณ โดยไม่มีความยุ่งยาก',
      'valPropTile1Title': '1. เรียนรู้หัวข้อใดก็ได้ใน 1 คลิก',
      'valPropTile1Desc':
          'ลืมการเสียเวลาสร้างคำถามด้วยตนเองไปได้เลย เลือกหัวข้อจากรายการแนะนำของเรา (เช่น การรับรอง AWS, Python, ENEM หรือกฎหมาย) หรือพิมพ์วิชาที่คุณต้องการเชี่ยวชาญ',
      'valPropTile2Title': '2. เรียนรู้ด้วยเนื้อหาของคุณเอง',
      'valPropTile2Desc':
          'มี PDF ยาว ไฟล์เสียงบรรยาย MP3 เอกสาร Word หรือสเปรดชีตหรือไม่ เพียงอัปโหลดไฟล์และเลือกบทหรือนาทีที่คุณต้องการทบทวน',
      'valPropTile3Title': '3. อินเทอร์เฟซที่เรียบง่ายสไตล์ Apple',
      'valPropTile3Desc':
          'ออกแบบมาเพื่อประสิทธิภาพสูงสุด ประสบการณ์ภาพที่ทันสมัย สะอาดตา และราบรื่นใน 4 ขั้นตอนง่ายๆ เปลี่ยนขั้นตอนเมื่อใดก็ได้โดยไม่สูญเสียข้อมูลที่กรอกไว้',
      'valPropTile4Title':
          '4. แดชบอร์ดอัจฉริยะและการเริ่มต่ออย่างรวดเร็ว',
      'valPropTile4Desc':
          'ต้องหยุดการเรียนชั่วคราวหรือไม่ ฉบับร่างของคุณจะได้รับการบันทึกโดยอัตโนมัติ ด้วย 1 คลิก กลับมาเรียนต่อจากจุดที่คุณค้างไว้ได้ทันที',
      'valPropTile5Title':
          '5. แชร์อย่างปลอดภัยและแข่งขันในตารางคะแนน',
      'valPropTile5Desc':
          'สร้างแบบทดสอบส่วนตัวพร้อมลิงก์ที่ปลอดภัยซึ่งหมดอายุโดยอัตโนมัติ หรือเผยแพร่แบบทดสอบของคุณในแคตตาล็อกชุมชน Asodya และแข่งขันในตารางคะแนนอย่างเป็นทางการ!',
      'valPropCtaGetStarted': '✨ เริ่มต้นใช้งานฟรี',
      'valPropCtaJoinWaitlist': '📋 เข้าร่วมรายการรอ Pro',
      'step1Title': '1. เลือกหัวข้อของคุณ',
      'step2Title': '2. เลือกแหล่งข้อมูล',
      'step3Title': '3. รูปแบบและความยาก',
      'step4Title': '4. ตรวจสอบและสร้าง',
      'sourceUpload': 'อัปโหลดเนื้อหาของฉันเอง',
      'questionCount': 'จำนวนคำถาม',
      'questionsSuffixLabel': 'คำถาม',
      'generateQuizNow': 'สร้างแบบทดสอบตอนนี้',
      'resetWizard': 'รีเซ็ตตัวช่วยสร้าง',
      'resetWizardConfirm':
          'การดำเนินการนี้จะล้างความคืบหน้าทั้งหมดและกลับไปที่ขั้นตอนที่ 1 ไม่สามารถย้อนกลับได้',
      'wizardTitle': 'สร้างแบบทดสอบใหม่',
      'studyNameHint': 'เช่น สถาปัตยกรรมซอฟต์แวร์ / ชีววิทยาของเซลล์',
      'sourceUploadHint': 'PDF, DOCX, CSV, TXT, MD, MP3, WAV, M4A, MP4, MOV',
      'difficultyLabel': 'ระดับความยาก:',
      'reviewThemeLabel': '📌 หัวข้อ:',
      'reviewSourceLabel': '📄 แหล่งข้อมูล:',
      'reviewLevelLabel': '🎯 ระดับ:',
      'reviewVisibilityLabel': '🔒 การมองเห็น:',
      'reviewFilesCountLabel': '{count} ไฟล์: {names}',
      'rangeSelectorTitle': 'คุณต้องการใช้ส่วนใด?',
      'pageStartLabel': 'หน้าเริ่มต้น',
      'pageEndLabel': 'หน้าสิ้นสุด',
      'rangeUntil': 'ถึง',
      'lineStartLabel': 'บรรทัดเริ่มต้น',
      'lineEndLabel': 'บรรทัดสิ้นสุด',
      'timeRangeLabel': 'ช่วงเวลา:',
      'removeFile': 'ลบไฟล์',
      'addFiles': 'เพิ่มไฟล์',
      'filesCapUsageLabel': 'ใช้ไป {used} MB จาก {cap} MB',
      'capExceededWarning': 'การเพิ่มไฟล์นี้จะเกินขีดจำกัด 150MB ของการเรียนนี้',
      'tapFileToConfigureHint': 'แตะไฟล์เพื่อเลือกช่วงเฉพาะแทนเอกสารทั้งหมด',
      'noFilesAddedYet': 'ยังไม่มีไฟล์ที่เพิ่ม แตะเพิ่มไฟล์เพื่อเริ่มต้น',
      'questionCountMax': 'สูงสุด',
      'questionCountMaxLabel': 'มากที่สุดเท่าที่เนื้อหารองรับ',
      'visibilityPublicWarning':
          'เมื่อมีผู้อื่นทำแบบทดสอบสาธารณะนี้แล้ว จะไม่สามารถลบได้อีก เพื่อรักษาประวัติตารางคะแนน',
      'completedMetrics': 'เมตริกที่เสร็จสิ้น',
      'standbyStudies': 'การเรียนที่รอดำเนินการ',
      'quickInfo': 'ข้อมูลด่วน',
      'addFile': 'เพิ่มไฟล์',
      'startQuiz': 'เริ่มแบบทดสอบ',
      'cortexConnected': 'เชื่อมต่อ AI Cortex แล้ว',
      'studyNotebooksLabel': 'สมุดการเรียน',
      'storageUsedLabel': 'พื้นที่จัดเก็บ FSM ที่ใช้',
      'completedQuizzesLabel': 'แบบทดสอบที่เสร็จสิ้น',
      'averageScoreLabel': 'คะแนนเฉลี่ย',
      'noScoreDataTooltip': 'ยังไม่มีแบบทดสอบที่เสร็จสิ้น จึงยังไม่มีคะแนนเฉลี่ย',
      'dashboardEmptyState': 'แดชบอร์ดของคุณจะมีชีวิตชีวาทันทีที่คุณเริ่มการเรียน',
      'studiesBreakdownTooltip': 'รอดำเนินการ {standby} รายการ เสร็จสิ้น {completed} รายการ',
      'deleteStudyConfirm': 'คุณต้องการลบการเรียน "{name}" จริงหรือไม่?',
      'studyDeletedSuccess': 'ลบการเรียนเรียบร้อยแล้ว',
      'fileAttachedSuccess': 'แนบไฟล์เรียบร้อยแล้ว',
      'attachedSourcesLabel': 'ไฟล์และแหล่งข้อมูลที่แนบ ({count}):',
      'noFilesAttachedYet': 'ยังไม่มีไฟล์แนบ',
      'mbUsedLabel': 'MB ที่ใช้',
      'lastOpenedLabel': 'เปิดล่าสุดเมื่อ: {date}',
      'noStudiesSubtitle': 'สร้างการเรียนแรกของคุณเพื่อเริ่มต้น',
      'selectStudiesAction': 'เลือก',
      'selectedCountLabel': 'เลือกแล้ว {count} รายการ',
      'deleteSelectedAction': 'ลบรายการที่เลือก',
      'deleteSelectedConfirm': 'ลบการเรียน {count} รายการที่เลือกใช่หรือไม่ ไม่สามารถย้อนกลับได้',
      'searchStudiesHint': 'ค้นหาการเรียนของคุณ…',
      'noSearchResultsLabel': 'ไม่พบการเรียนที่ตรงกับ "{query}"',
      'editStudy': 'แก้ไขการเรียน',
      'renameStudyLabel': 'ชื่อการเรียน',
      'saveChanges': 'บันทึกการเปลี่ยนแปลง',
      'resumeHeroTitle': 'เริ่มต่อจากจุดที่คุณค้างไว้',
      'resumeHeroSubtitle':
          'กลับไปทำฉบับร่างล่าสุดต่อจากจุดที่คุณหยุดไว้',
      'resumeHeroCta': 'เริ่มต่อเลย',
      'editSourceRangesLabel': 'ช่วงที่เลือกไว้',
      'expiration24h': '24 ชั่วโมง (ระยะสั้น)',
      'expiration7d': '7 วัน (1 สัปดาห์)',
      'expiration30d': '30 วัน (1 เดือน)',
      'expirationOneUse': 'ใช้ได้ครั้งเดียว',
      'expirationLabel': 'เวลาหมดอายุของลิงก์:',
      'shareModalSubtitle': 'แชร์: "{title}"',
      'generateSecureLink': 'สร้างลิงก์ที่ปลอดภัยและหมดอายุได้',
      'regenerateLink': 'สร้างลิงก์ใหม่',
      'linkCopied': 'คัดลอกลิงก์ไปยังคลิปบอร์ดแล้ว!',
      'noParticipantsYet': 'ยังไม่มีผู้เข้าร่วมทำแบบทดสอบนี้เสร็จ',
      'timePrefix': 'เวลา:',
      'visibilityLabel': 'การมองเห็น',
      'visibilityPrivate': 'ส่วนตัว',
      'visibilityPublic': 'สาธารณะ',
      'deleteProtectedTooltip':
          'ไม่สามารถลบแบบทดสอบสาธารณะที่มีผู้เข้าร่วมทำอยู่ได้ เพื่อรักษาประวัติตารางคะแนน',
      'completedQuizzesTitle': 'แบบทดสอบที่เสร็จสิ้น',
      'shareLink': 'แชร์ลิงก์',
      'leaderboard': 'ตารางคะแนน',
      'shareAction': 'แชร์',
      'leaderboardAction': 'ดูตารางคะแนน',
      'viewCompletedQuizzes': 'ดูแบบทดสอบที่เสร็จสิ้น',
      'noCompletedQuizzesYet': 'คุณยังไม่มีแบบทดสอบที่เสร็จสิ้น',
      'yourCertificatesLabel': 'ใบรับรองของคุณ',
      'expandDashboard': 'ขยาย',
      'collapseDashboard': 'ย่อ',
      'completedOnLabel': 'เสร็จสิ้นเมื่อ',
      'totalAttemptsLabel': 'จำนวนครั้งที่ทำทั้งหมด',
    },
  };
  String text(String key) =>
      _copy[locale.languageCode]?[key] ?? _copy['en']?[key] ?? key;
  static AppLocalizations of(BuildContext context) =>
      Localizations.of<AppLocalizations>(context, AppLocalizations) ??
      const AppLocalizations(Locale('en'));
}

class AppLocalizationsDelegate extends LocalizationsDelegate<AppLocalizations> {
  const AppLocalizationsDelegate();
  @override
  bool isSupported(Locale locale) => AppLocalizations.supportedLocales.any(
    (item) => item.languageCode == locale.languageCode,
  );
  @override
  Future<AppLocalizations> load(Locale locale) async =>
      AppLocalizations(locale);
  @override
  bool shouldReload(AppLocalizationsDelegate old) => false;
}

extension Translation on BuildContext {
  String tr(String key) => AppLocalizations.of(this).text(key);

  /// Resolves [key] and replaces `{placeholder}` tokens with the matching
  /// value from [params], e.g. `trParams('deleteStudyConfirm', {'name': study.name})`.
  String trParams(String key, Map<String, String> params) {
    var value = tr(key);
    params.forEach((token, replacement) {
      value = value.replaceAll('{$token}', replacement);
    });
    return value;
  }
}

class FallbackMaterialLocalizationsDelegate
    extends LocalizationsDelegate<MaterialLocalizations> {
  const FallbackMaterialLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) => true;

  @override
  Future<MaterialLocalizations> load(Locale locale) async =>
      DefaultMaterialLocalizations();

  @override
  bool shouldReload(FallbackMaterialLocalizationsDelegate old) => false;
}
