import 'package:flutter/widgets.dart';

class AppLocalizations {
  const AppLocalizations(this.locale);
  final Locale locale;
  static const supportedLocales = [Locale('en'), Locale('pt'), Locale('th')];
  static const _copy = {
    'en': {
      'appName': 'Certifications',
      'about': 'About',
      'logIn': 'Log in',
      'signUp': 'Sign up',
      'close': 'Close',
      'certificates': 'Certificates',
      'plans': 'Plans',
      'support': 'Support',
      'profile': 'Profile',
      'logout': 'Logout',
      'landingImagine': 'Imagine sharing a',
      'landingExample': 'Certified Master of Shrek Quotes',
      'landingCertification': 'certification.',
      'landingSeriousQuestion': 'Or your layer is serious certifications?',
      'landingSeriousBody': 'This is your growth hack entry point.',
      'welcomeTitle': 'Turn material into mastery.',
      'welcomeBody': 'Build a focused study from the material you choose.',
      'signIn': 'Sign in',
      'openStudies': 'Open studies',
      'newStudy': 'New study',
      'studyName': 'Study name',
      'createStudy': 'Create study',
      'yourStudies': 'Your studies',
      'noStudies': 'No studies yet',
      'continueStudy': 'Continue',
      'addSource': 'Add source',
      'upload': 'Upload',
      'pdf': 'PDF',
      'audio': 'Audio',
      'text': 'Text',
      'selectRange': 'Select range',
      'process': 'Process source',
      'ready': 'Ready',
      'processing': 'Processing',
      'generate': 'Generate questions',
      'useWeb': 'Use web research',
      'useWebDescription':
          'Allow this quiz generation to use web research when needed.',
      'easy': 'Easy',
      'medium': 'Medium',
      'hard': 'Hard',
      'theme': 'Theme',
      'language': 'Language',
      'appearanceAndLanguage': 'Appearance & language',
      'darkTheme': 'Dark theme',
      'themeDescription':
          'Switch between the light and dark monochrome themes.',
      'system': 'System',
      'light': 'Light',
      'dark': 'Dark',
      'remaining': 'Remaining',
      'delete': 'Delete',
      'complete': 'Complete study',
      'errorGeneric': 'Something went wrong. Please try again.',
      'retry': 'Retry',
      'loading': 'Loading…',
      'question': 'Question',
      'next': 'Next',
      'finish': 'Finish',
      'diagramUnavailable': 'Diagram unavailable',
      'studyComplete': 'Study completed',
      'memory': 'Study memory',
      'trustTransparency': 'Trust & transparency',
      'trustTitle': 'No provider keys required',
      'trustBody':
          'Certification generation is managed by the application. You never need to paste a model provider key.',
      'privacyTitle': 'Privacy, simply stated',
      'privacyBody':
          'We use your sources only to create your study. Share only what you are comfortable sharing.',
      'planFree': 'Free · MVP',
      'plansIntro':
          'Free during the MVP — start a focused study with managed local capacity.',
      'planStudyTitle': 'Study without configuration',
      'planStudyBody':
          'Create a study from your material, generate questions, and finish with a shareable certification.',
      'tier0Capacity': 'Tier 0 · default local capacity',
      'tier12Allowance': 'Tiers 1–2 · small guided allowance',
      'tier35Trial': 'Tiers 3–5 · limited trial capacity',
      'selectPlan': 'Select plan',
      'joinWaitlist': 'Join the waitlist',
      'waitlistTitle': 'Join the waitlist',
      'waitlistBody':
          'Leave your email and we will keep your place for upcoming plan access.',
      'email': 'Email',
      'emailInvalid': 'Enter a valid email address.',
      'waitlistSuccess': 'Your request was received.',
      'waitlistFailure':
          'We could not record your request. Please try again later.',
      'submit': 'Submit',
      'cancel': 'Cancel',
      'planGuided': 'Guided',
      'planAdvanced': 'Advanced',
      'planGuidedBody':
          'More guided generation and study controls are planned for a future release.',
      'planAdvancedBody':
          'Higher tiers and expanded limits will arrive after the MVP.',
      'planComingSoon': 'Coming soon',
      'planUnavailable': 'Selection is not available yet.',
    },
    'pt': {
      'appName': 'Certifications',
      'about': 'Sobre',
      'logIn': 'Entrar',
      'signUp': 'Criar conta',
      'close': 'Fechar',
      'certificates': 'Certificados',
      'plans': 'Planos',
      'support': 'Suporte',
      'profile': 'Perfil',
      'logout': 'Sair',
      'landingImagine': 'Imagine compartilhar uma',
      'landingExample': 'Mestre Certificado em Frases do Shrek',
      'landingCertification': 'certificação.',
      'landingSeriousQuestion': 'Ou a sua área exige certificações sérias?',
      'landingSeriousBody': 'Este é o ponto de partida para seu crescimento.',
      'welcomeTitle': 'Transforme material em domínio.',
      'welcomeBody': 'Crie um estudo focado com o material que você escolher.',
      'signIn': 'Entrar',
      'openStudies': 'Abrir estudos',
      'newStudy': 'Novo estudo',
      'studyName': 'Nome do estudo',
      'createStudy': 'Criar estudo',
      'yourStudies': 'Seus estudos',
      'noStudies': 'Nenhum estudo ainda',
      'continueStudy': 'Continuar',
      'addSource': 'Adicionar fonte',
      'upload': 'Enviar',
      'pdf': 'PDF',
      'audio': 'Áudio',
      'text': 'Texto',
      'selectRange': 'Selecionar trecho',
      'process': 'Processar fonte',
      'ready': 'Pronto',
      'processing': 'Processando',
      'generate': 'Gerar perguntas',
      'useWeb': 'Usar pesquisa na web',
      'useWebDescription':
          'Permite que esta geração use pesquisa na web quando necessário.',
      'easy': 'Fácil',
      'medium': 'Médio',
      'hard': 'Difícil',
      'theme': 'Tema',
      'language': 'Idioma',
      'appearanceAndLanguage': 'Aparência e idioma',
      'darkTheme': 'Tema escuro',
      'themeDescription':
          'Alterne entre os temas monocromáticos claro e escuro.',
      'system': 'Sistema',
      'light': 'Claro',
      'dark': 'Escuro',
      'remaining': 'Restante',
      'delete': 'Excluir',
      'complete': 'Concluir estudo',
      'errorGeneric': 'Algo deu errado. Tente novamente.',
      'retry': 'Tentar novamente',
      'loading': 'Carregando…',
      'question': 'Pergunta',
      'next': 'Próxima',
      'finish': 'Finalizar',
      'diagramUnavailable': 'Diagrama indisponível',
      'studyComplete': 'Estudo concluído',
      'memory': 'Memória do estudo',
      'trustTransparency': 'Confiança e transparência',
      'trustTitle': 'Nenhuma chave de provedor necessária',
      'trustBody':
          'A geração da certificação é gerenciada pelo aplicativo. Você não precisa colar uma chave de provedor.',
      'privacyTitle': 'Privacidade sem complicação',
      'privacyBody':
          'Usamos suas fontes apenas para criar seu estudo. Compartilhe somente o que se sentir confortável.',
      'planFree': 'Grátis · MVP',
      'plansIntro':
          'Grátis durante o MVP — comece um estudo focado com capacidade local gerenciada.',
      'planStudyTitle': 'Estude sem configuração',
      'planStudyBody':
          'Crie um estudo com seu material, gere perguntas e conclua com uma certificação compartilhável.',
      'tier0Capacity': 'Tier 0 · capacidade local padrão',
      'tier12Allowance': 'Tiers 1–2 · pequena cota guiada',
      'tier35Trial': 'Tiers 3–5 · capacidade de teste limitada',
      'selectPlan': 'Selecionar plano',
      'joinWaitlist': 'Entrar na lista de espera',
      'waitlistTitle': 'Entrar na lista de espera',
      'waitlistBody':
          'Informe seu e-mail para reservar seu lugar no acesso aos próximos planos.',
      'email': 'E-mail',
      'emailInvalid': 'Informe um e-mail válido.',
      'waitlistSuccess': 'Sua solicitação foi recebida.',
      'waitlistFailure':
          'Não foi possível registrar sua solicitação. Tente novamente mais tarde.',
      'submit': 'Enviar',
      'cancel': 'Cancelar',
      'planGuided': 'Guiado',
      'planAdvanced': 'Avançado',
      'planGuidedBody':
          'Geração mais guiada e novos controles de estudo estão planejados para uma versão futura.',
      'planAdvancedBody':
          'Tiers mais altos e limites ampliados chegarão depois do MVP.',
      'planComingSoon': 'Em breve',
      'planUnavailable': 'A seleção ainda não está disponível.',
    },
    'th': {
      'appName': 'Certifications',
      'about': 'เกี่ยวกับ',
      'logIn': 'เข้าสู่ระบบ',
      'signUp': 'สมัครใช้งาน',
      'close': 'ปิด',
      'certificates': 'ใบรับรอง',
      'plans': 'แผน',
      'support': 'ช่วยเหลือ',
      'profile': 'โปรไฟล์',
      'logout': 'ออกจากระบบ',
      'landingImagine': 'ลองนึกภาพการแชร์',
      'landingExample': 'ผู้เชี่ยวชาญคำคมเชร็คที่ได้รับการรับรอง',
      'landingCertification': 'ใบรับรอง',
      'landingSeriousQuestion': 'หรือสาขาของคุณต้องการใบรับรองที่จริงจัง?',
      'landingSeriousBody': 'นี่คือจุดเริ่มต้นของการเติบโตของคุณ',
      'welcomeTitle': 'เปลี่ยนเนื้อหาให้เป็นความเชี่ยวชาญ',
      'welcomeBody': 'สร้างการเรียนรู้ที่มีสมาธิจากเนื้อหาที่คุณเลือก',
      'signIn': 'เข้าสู่ระบบ',
      'openStudies': 'เปิดการเรียน',
      'newStudy': 'การเรียนใหม่',
      'studyName': 'ชื่อการเรียน',
      'createStudy': 'สร้างการเรียน',
      'yourStudies': 'การเรียนของคุณ',
      'noStudies': 'ยังไม่มีการเรียน',
      'continueStudy': 'ดำเนินการต่อ',
      'addSource': 'เพิ่มแหล่งข้อมูล',
      'upload': 'อัปโหลด',
      'pdf': 'PDF',
      'audio': 'เสียง',
      'text': 'ข้อความ',
      'selectRange': 'เลือกช่วง',
      'process': 'ประมวลผลแหล่งข้อมูล',
      'ready': 'พร้อม',
      'processing': 'กำลังประมวลผล',
      'generate': 'สร้างคำถาม',
      'useWeb': 'ใช้การค้นหาบนเว็บ',
      'useWebDescription':
          'อนุญาตให้การสร้างแบบทดสอบนี้ใช้การค้นหาบนเว็บเมื่อจำเป็น',
      'easy': 'ง่าย',
      'medium': 'ปานกลาง',
      'hard': 'ยาก',
      'theme': 'ธีม',
      'language': 'ภาษา',
      'appearanceAndLanguage': 'รูปแบบและภาษา',
      'darkTheme': 'ธีมมืด',
      'themeDescription': 'สลับระหว่างธีมขาวดำสว่างและมืด',
      'system': 'ระบบ',
      'light': 'สว่าง',
      'dark': 'มืด',
      'remaining': 'คงเหลือ',
      'delete': 'ลบ',
      'complete': 'เรียนจบ',
      'errorGeneric': 'เกิดข้อผิดพลาด โปรดลองอีกครั้ง',
      'retry': 'ลองอีกครั้ง',
      'loading': 'กำลังโหลด…',
      'question': 'คำถาม',
      'next': 'ถัดไป',
      'finish': 'เสร็จสิ้น',
      'diagramUnavailable': 'แผนภาพไม่พร้อมใช้งาน',
      'studyComplete': 'เรียนจบแล้ว',
      'memory': 'ความจำการเรียน',
      'trustTransparency': 'ความน่าเชื่อถือและความโปร่งใส',
      'trustTitle': 'ไม่ต้องใช้คีย์ผู้ให้บริการ',
      'trustBody':
          'แอปจัดการการสร้างใบรับรองให้เอง คุณไม่จำเป็นต้องวางคีย์ของผู้ให้บริการโมเดล',
      'privacyTitle': 'ความเป็นส่วนตัวอย่างชัดเจน',
      'privacyBody':
          'เราใช้แหล่งข้อมูลของคุณเพื่อสร้างการเรียนเท่านั้น แชร์เฉพาะสิ่งที่คุณสบายใจ',
      'planFree': 'ฟรี · MVP',
      'plansIntro':
          'ฟรีในช่วง MVP — เริ่มการเรียนรู้แบบโฟกัสด้วยความจุในเครื่อง',
      'planStudyTitle': 'เรียนรู้โดยไม่ต้องตั้งค่า',
      'planStudyBody':
          'สร้างการเรียนจากเนื้อหา สร้างคำถาม และจบด้วยใบรับรองที่แชร์ได้',
      'tier0Capacity': 'Tier 0 · ความจุในเครื่องเริ่มต้น',
      'tier12Allowance': 'Tier 1–2 · โควตาแนะนำขนาดเล็ก',
      'tier35Trial': 'Tier 3–5 · ความจุทดลองแบบจำกัด',
      'selectPlan': 'เลือกแผน',
      'joinWaitlist': 'เข้าร่วมรายการรอ',
      'waitlistTitle': 'เข้าร่วมรายการรอ',
      'waitlistBody': 'กรอกอีเมลเพื่อรับสิทธิ์เข้าถึงแผนในอนาคต',
      'email': 'อีเมล',
      'emailInvalid': 'กรุณากรอกอีเมลที่ถูกต้อง',
      'waitlistSuccess': 'ได้รับคำขอของคุณแล้ว',
      'waitlistFailure': 'ไม่สามารถบันทึกคำขอได้ โปรดลองอีกครั้งภายหลัง',
      'submit': 'ส่ง',
      'cancel': 'ยกเลิก',
      'planGuided': 'แนะนำ',
      'planAdvanced': 'ขั้นสูง',
      'planGuidedBody':
          'การสร้างที่มีคำแนะนำมากขึ้นและการควบคุมการเรียนจะมาในรุ่นถัดไป',
      'planAdvancedBody': 'Tier ที่สูงขึ้นและขีดจำกัดที่เพิ่มขึ้นจะมาหลัง MVP',
      'planComingSoon': 'เร็ว ๆ นี้',
      'planUnavailable': 'ยังไม่สามารถเลือกได้',
    },
  };
  String text(String key) =>
      _copy[locale.languageCode]?[key] ?? _copy['en']![key] ?? key;
  static AppLocalizations of(BuildContext context) =>
      Localizations.of<AppLocalizations>(context, AppLocalizations) ??
      const AppLocalizations(Locale('en'));
}

class AppLocalizationsDelegate extends LocalizationsDelegate<AppLocalizations> {
  const AppLocalizationsDelegate();
  @override
  bool isSupported(Locale locale) => AppLocalizations.supportedLocales.any(
    (item) => item.languageCode == locale.languageCode,
  );
  @override
  Future<AppLocalizations> load(Locale locale) async =>
      AppLocalizations(locale);
  @override
  bool shouldReload(AppLocalizationsDelegate old) => false;
}

extension Translation on BuildContext {
  String tr(String key) => AppLocalizations.of(this).text(key);
}
